# Universidad del Valle de Guatemala
## Security Data Science - 10
* Juan Manuel Marroquin Alfaro - 19845
* Carlos Alberto Raxtum Ramos - 19721
* Jose Abraham Gutierrez Corado - 19111
* Walter Danilo Saldaña Salguero - 19897
* Javier Alejandro Cotto Argueta - 19324

## Proyecto Fase 2: Selección de caracteristicas y limpieza de datos

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np
import sklearn.cluster as cluster
from sklearn.cluster import KMeans
import itertools
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
from yellowbrick.cluster import SilhouetteVisualizer
from os import listdir
from os.path import isfile, join
import os

## Normal Images

In [2]:
df1 = pd.read_csv('normal_images_info.csv', header = None)
df1.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,65527,65528,65529,65530,65531,65532,65533,65534,65535,65536
221,220.0,239,240,240,241,241,242,244,245,247,...,17,34,62,87,66,42,172,77,8,16
66,65.0,38,29,34,39,32,31,27,35,29,...,104,106,103,92,87,107,105,105,112,110
526,525.0,42,43,42,41,37,34,31,28,27,...,48,49,52,63,72,82,90,99,106,104
578,577.0,18,12,12,17,21,21,21,25,21,...,136,137,137,138,136,136,137,139,138,135
854,853.0,109,109,112,111,109,107,107,106,104,...,75,82,84,82,75,69,45,14,7,9

### Observaciones del Dataframe de Imagenes Normales

In [3]:
df1.shape

(1001, 65537)

## Stego Images

In [4]:
df2 = pd.read_csv('infected_images_info.csv', header = None)
df2.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,65527,65528,65529,65530,65531,65532,65533,65534,65535,65536
338,337.0,39,30,33,29,29,32,33,29,23,...,51,40,59,51,43,63,72,62,46,55
763,762.0,88,88,92,95,96,93,93,96,98,...,60,61,62,65,66,66,68,67,70,75
468,467.0,101,101,102,102,103,101,101,83,88,...,9,14,101,176,41,4,8,11,15,19
907,906.0,11,12,19,19,34,26,13,15,15,...,83,96,107,95,89,89,72,72,79,85
60,59.0,12,13,14,12,14,16,15,14,12,...,6,6,6,5,6,6,6,6,6,7

### Observaciones del Dataframe de Imagenes Alteradas

In [5]:
df2.shape

(1001, 65537)

## Dataframe Completo

Concatenación de los dataframes

In [6]:
#1 Si tiene 0 No tiene
df1['isInfected'] = 0
df2['isInfected'] = 1

df  = pd.concat([df1, df2])
df

,0,1,2,3,4,5,6,7,8,9,...,65528,65529,65530,65531,65532,65533,65534,65535,65536,isInfected
0,NaN,0,1,2,3,4,5,6,7,8,...,65527,65528,65529,65530,65531,65532,65533,65534,65535,0
1,0.0,81,77,81,82,79,82,81,79,81,...,19,20,22,22,17,17,17,22,24,0
2,1.0,6,5,5,6,5,5,5,5,5,...,5,6,5,5,5,5,5,5,5,0
3,2.0,15,16,16,17,16,15,16,16,16,...,18,22,23,15,12,11,12,12,12,0
4,3.0,97,99,96,93,92,93,92,91,91,...,48,60,69,65,61,58,50,49,53,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,995.0,11,13,15,22,26,24,24,23,24,...,88,88,87,86,87,87,88,87,86,1
997,996.0,66,63,63,62,60,59,49,65,76,...,180,178,187,169,150,137,165,148,85,1
998,997.0,86,87,89,91,84,91,91,88,91,...,58,49,51,58,44,44,45,39,44,1
999,998.0,129,128,150,174,159,162,157,144,130,...,103,102,103,100,88,84,84,76,27,1
1000,999.0,16,14,14,18,14,10,10,6,12,...,14,19,20,19,23,19,13,14,8,1

### Observaciones del Dataframe completo

In [7]:
df.shape

(2002, 65538)

## Partimos el SET (entrenamiento 55%, validación 15%, prueba 30%)

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [10]:
X = df.drop(columns = ['isInfected']).copy()
y = df['isInfected']

#Dividiremos nuestros datos en dos gran conjuntos(entrenamiento y data restante)
x_train, x_rem, y_train, y_rem = train_test_split(X, y, train_size = 0.55, random_state = 0)
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1101 entries, 654 to 684
Columns: 65537 entries, 0 to 65536
dtypes: float64(1), int64(65536)
memory usage: 550.5 MB

In [11]:
#Dividiremos nuestros datos en dos gran conjuntos(validación y prueba)
#45% -> 100
#30% -> x
#x = 66.67
x_valid, x_test, y_valid, y_test = train_test_split(x_rem, y_rem, test_size = 0.66, random_state = 0)
x_valid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 306 entries, 452 to 473
Columns: 65537 entries, 0 to 65536
dtypes: float64(1), int64(65536)
memory usage: 153.0 MB

### Observaciones de los conjuntos de Entrenamiento, Validación y Prueba

In [14]:
print("X train shape: ", x_train.shape)
print("Y train shape: ", y_train.shape)
print("X valid shape: ", x_valid.shape)
print("Y valid shape: ", y_valid.shape)
print("X test shape: ", x_test.shape)
print("Y test shape: ", y_test.shape)

X train shape:  (1101, 65537)
Y train shape:  (1101,)
X valid shape:  (306, 65537)
Y valid shape:  (306,)
X test shape:  (595, 65537)
Y test shape:  (595,)

### Modelos Naive Bayes

In [15]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
y_pred = gnb.fit(x_train, y_train).predict(x_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').